# Generated by Django 5.2.8 on 2026-03-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreforge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_faction', to='loreforge.character'),
        ),
    ]
